# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*
    - !!js/regexp ^\.fa-home
    - !!js/regexp ^\.fa-question-circle
    - !!js/regexp ^\.fa-external-link
    - !!js/regexp ^\.fa-book
    - !!js/regexp ^\.orbit*
    - !!js/regexp ^\.slide*
    - !!js/regexp ^\.mui*
    - !!js/regexp .clean-hero-slider

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss,seo}/**/*"
    # Next two lines add location of FontAwesome font assets.
    - "node_modules/font-awesome/**/*"
    - "!node_modules/font-awesome/{css,less,scss}/**/*"

  # Assets per i file robots, .htaccess, etc...  
  seoassets:
    - "src/assets/seo/*"
    - "src/assets/seo/.htaccess"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
    # Next line adds FontAwesome SCSS assets
    - "node_modules/font-awesome/scss"

  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
